### ISSUE TITLE
X+whatever

### ISSUE THREAD

**Issue by FlexGamesGitHub** [mwageringel/everest#10]
Wouldn't it make more sense if `X+9` for example was `9` as `10+9` is `19` and without the first digit it's `9`?
Sure it would then be too easy to find the solution but it would make sense.

And also why is `0-3` `8`? This only makes sense if you think unlogical 2 times

**Comment by andyp1xe1** [comment]
Spoiler!
The system of this game is a wheel, where 10 is the highest number, and also the lowest.
so X is 10 and also -1, depending your point of reference.
Think of a clock with 11 hours, from 0 to X:
0 - 3 would be moving counter-clockwise 3 times from 0, so 11 - 3, which is 8.

**Comment by mwageringel** [comment]
> Wouldn't it make more sense if `X+9` for example was `9` as `10+9` is `19` and without the first digit it's `9`? Sure it would then be too easy to find the solution but it would make sense.

Hi @FlexGamesGitHub What you describe makes a lot of sense, too, and it is possible to work with such a system.

The way the game currently works allows for some challenges later on that would not be possible otherwise though (due to some mathematical properties). This only starts to become relevant from Level 5 onwards. Once you have completed Level 5, you might want to try to think of why `1/2=?` could not have an answer in the 10-based system, but it does in the 11-based system.

**Comment by FlexGamesGitHub** [comment]
Well this seems complicated. So, I think its a good idea but it destroys your math skills
