### ISSUE TITLE
Can't proceed on level 1

### ISSUE THREAD

**Issue by donkeyDau** [mwageringel/everest#15]
No digit is working. Started with 8 and then tried all other. All get a red cross. Don't know if I just don't get it or it's a bug
![Screenshot_20220903-183331_Everest](https://user-images.githubusercontent.com/17231336/188281079-b1e8b441-0b56-4f75-ae3f-df00f6fb4aa6.png)

**Comment by mwageringel** [comment]
Hi @donkeyDau, thanks for the feedback. This one only turns green when all three answers in that group are correct. You are already close to the solution, but the second answer is not quite correct yet.

**Comment by revuwa** [comment]
@donkeyDau 
I initially thought exactly the same, but let me say it's definitively possible to solve, (with the correct results).

**Comment by donkeyDau** [comment]
@mwageringel @revuwa Thanks a lot. I figured it out with your hint. The feedback is what tricked me. I was not aware that the validation is for all 3 items but not only the last. Maybe it's possible to improve on that?

**Comment by mwageringel** [comment]
A small change that I could implement would be to make the cursor jump back to the first answer when the red cross appears, instead of staying at the third answer. This might already make it a bit clearer that all three of the answers need to be reconsidered. I'm open to other ideas as well.

**Comment by donkeyDau** [comment]
This would be an improvement but from UX perspective still unsatisfying. The user might think that the first equation is wrong (in my case it wasn't) and be still confused. Why not show check mark or cross on each equation?

**Comment by mwageringel** [comment]
> Why not show check mark or cross on each equation?

If one of the answers is wrong, the game does not reveal which one it is in order to discourage from advancing to the next levels by trying all possible combinations. That would make it more difficult to figure out and understand the solutions of the later levels.

Here's another idea. Instead of immediately showing the cross or check mark on each equation, the icon is covered up as in the picture. If all three answers are correct, they simultaneously switch to the green check mark. If an answer is wrong, the icons stay covered and all show the wiggly animation to indicate that something is wrong.

It's hard to tell if this would be intuitive enough, but at least this notifies the player that something is different than before.
![image](https://user-images.githubusercontent.com/39632129/188708561-bbd9ea76-6176-4d49-b741-d092f0836082.png)

**Comment by mwageringel** [comment]
![](https://user-images.githubusercontent.com/39632129/189487316-a9a7a911-34fd-443b-8230-9a362f68e7b1.png)
I have just pushed my changes. This is what it is going to look like after the next update. Thanks again for the feedback, which was quite helpful.

**Comment by donkeyDau** [comment]
Wow. Looks perfect! Thank you!
