### ISSUE TITLE
X isn't specified

### ISSUE THREAD

**Issue by Rafael000000** [mwageringel/everest#22]
I read an earlier issue where it was said that when the answer is 10 you should use X. But it is not specified that X = -1 aswell. 

Maybe it's an option to say that when the app starts for the first time?

**Comment by woklei** [comment]
The game is about exploring (and applying) a set of arithmetic rules. There is indeed a rule in this set which solves this issue.
So basically, your suggestion would reveal (a part of) the solution to the user before he even had a chance to think about it.

While one could argue about providing an option to see the solution (or a hint), I do not think it makes sense to show it on the first start.

**Comment by mwageringel** [comment]
Thank you both for your comments. To me, it seems important that a player notices the different meanings of X on their own. This is the main philosophy behind the game, as I think it is more rewarding and allows for a deeper understanding if a player finds this out on their own, rather than reading a hint that explains this (which would take away part of the challenge).

I understand that several players get stuck in level 1 trying to understand X or other mechanics of the game, but I'm hesitant to provide a direct hint at the solution, as it might keep players from developing a deep understanding. I'm more inclined to redesign the first levels to better introduce the concepts, along the lines of #21.
