### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by gabriblas** [mwageringel/everest#28]
Awesome game! I translated into Italian all the strings in the files you provided in the readme. Here they are: 

- [full_description.txt](https://github.com/mwageringel/everest/files/13992575/full_description.txt)
- [short_description.txt](https://github.com/mwageringel/everest/files/13992580/short_description.txt)
- [app_it.txt](https://github.com/mwageringel/everest/files/13992581/app_it.txt)

**Notice**: I didn't encode `extendedMessage` back to base64 because I didn't want to screw it up, but I can provide an encoded version.

**Comment by mwageringel** [comment]
Thanks, much appreciated.

Would you like to submit a Pull Request so that the changes get attributed to your account? You can create and edit files directly in your web browser after creating a fork of the repository.

Alternatively, I can commit the changes for you, but in order for them to be attributed to your account, I'd need to know the email address you use for Github commits, such as the `noreply` address, see [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address).

Also, I'm going to need a couple of days to sort out some build issues.

**Comment by gabriblas** [comment]
Pull requested submitted! (#29)
