### ISSUE TITLE
More challenges at level 5

### ISSUE THREAD

**Issue by RandomModderJDK** [mwageringel/everest#9]
Im stuck in level 5 and need a bit more challanges

**Comment by mwageringel** [comment]
Thanks for the feedback. Level 5 is indeed a bit short. I am going to add some more questions to it with the next update.

For the meantime, here is a small hint. Try to replace the numerators by something else.

**Comment by Hypoon** [comment]
Could these questions be procedurally generated?

**Comment by mwageringel** [comment]
> Could these questions be procedurally generated?

Yes, they could be generated randomly. So far, I've hand-picked the questions and put them in an order that I feel introduces the new concepts in each level well. So for many questions, the context in which they are asked is not random.

If what you have in mind is a button that generates additional questions on demand, that's really an interesting idea. It might alter the game play quite a bit. Though, for level 5 in particular the problem is that there is actually only a very small number of questions that fit into the context of the level. Most of them are included in the update 1.1.3.

(I'm going to respond to your other comments at another time.)

**Comment by Hypoon** [comment]
I imagined you might fix certain values to be zero or one, and then generate the other values randomly, or randomly within some criteria (perhaps you want the sum of two values to be larger or smaller than some particular number).

Unrestricted random generation is dangerous, since someone could abuse it to undermine the point of the three-question sections.

**Comment by mwageringel** [comment]
Version 1.1.3 is now available on F-Droid which includes more questions for level 5 as well as for some other levels. I hope this might help.

We can keep this issue open for a bit longer in case anyone has a similar request.
